"""empty message

Revision ID: 47e0c39b7f63
Revises: cf581739e3cb
Create Date: 2021-05-30 07:17:23.469014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e0c39b7f63'
down_revision = 'cf581739e3cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'status')
    # ### end Alembic commands ###
