"""Init DB

Revision ID: cf581739e3cb
Revises: 
Create Date: 2021-05-23 04:15:40.545781

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf581739e3cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verifies',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_email_verifies_uuid'), 'email_verifies', ['uuid'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('pays',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_pays_uuid'), 'pays', ['uuid'], unique=False)
    op.create_table('tests',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('external_id', sa.BigInteger(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('pay_uuid', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['pay_uuid'], ['pays.uuid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_tests_uuid'), 'tests', ['uuid'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('test_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('rubric', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('answers', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_index(op.f('ix_tests_uuid'), table_name='tests')
    op.drop_table('tests')
    op.drop_index(op.f('ix_pays_uuid'), table_name='pays')
    op.drop_table('pays')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_email_verifies_uuid'), table_name='email_verifies')
    op.drop_table('email_verifies')
    # ### end Alembic commands ###
