version: '3'
services:
  web:
    image: nginx:1.19
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - backend
      - frontend
    ports:
      - 127.0.0.1:${BACKEND_PORT}:80
  backend:
    build: ./backend
    volumes:
      - ./backend/src:/src
    depends_on:
      - db
    command: uvicorn app.main:app --reload --host 0.0.0.0
    environment:
      SECRET_KEY: ${SECRET_KEY}
      SERVER_HOST: ${SERVER_HOST}
      SERVER_NAME: ${SERVER_NAME}
      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS}
      PROJECT_NAME: ${PROJECT_NAME}
      POSTGRES_SERVER: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      FIRST_SUPERUSER: ${FIRST_SUPERUSER}
      FIRST_SUPERUSER_PASSWORD: ${FIRST_SUPERUSER_PASSWORD}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      EMAILS_FROM_EMAIL: ${EMAILS_FROM_EMAIL}
      EMAILS_FROM_NAME: ${EMAILS_FROM_NAME}
      QIWI_PUBLIC_KEY: ${QIWI_PUBLIC_KEY}
      QIWI_PRIVATE_KEY: ${QIWI_PRIVATE_KEY}

  frontend:
    build: ./frontend
  worker:
    build: ./backend
    command: celery -A app.core.celery_app.celery worker --loglevel=INFO
    volumes:
      - ./backend/src:/src
    depends_on:
      - db
    environment:
      SECRET_KEY: ${SECRET_KEY}
      SERVER_HOST: ${SERVER_HOST}
      SERVER_NAME: ${SERVER_NAME}
      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS}
      PROJECT_NAME: ${PROJECT_NAME}
      POSTGRES_SERVER: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      FIRST_SUPERUSER: ${FIRST_SUPERUSER}
      FIRST_SUPERUSER_PASSWORD: ${FIRST_SUPERUSER_PASSWORD}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      EMAILS_FROM_EMAIL: ${EMAILS_FROM_EMAIL}
      EMAILS_FROM_NAME: ${EMAILS_FROM_NAME}
      QIWI_PUBLIC_KEY: ${QIWI_PUBLIC_KEY}
      QIWI_PRIVATE_KEY: ${QIWI_PRIVATE_KEY}
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
  redis:
    image: redis:latest